name: TestSpigot
main: dev.minecode.core.testSpigot.TestSpigot
version: 0.1.0-Pre.1
api-version: 1.19
commands:
  testspigot:
    description: A test-command
    aliases:
      - ts
    usage: /testspigot